### ISSUE TITLE
Error occurs when running prebuilt app

### ISSUE THREAD

**Issue by ThisisBillhe** [BBuf/run-rwkv-world-4-in-mlc-llm#3]
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: ValueError: Check failed: shard_rec.nbytes == raw_data.length() (33233920 vs. 22720361) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation
Stack trace:
  File "/Users/bbuf/工作目录/RWKV/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 262

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:646)
	at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:644)
	at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:547)
	at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:644)
	at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
	at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

Error message:
ValueError: Check failed: shard_rec.nbytes == raw_data.length() (33233920 vs. 22720361) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation
Stack trace:
  File "/Users/bbuf/工作目录/RWKV/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 262

**Comment by BBuf** [comment]
> MLCChat failed
> 
> Stack trace: org.apache.tvm.Base$TVMError: ValueError: Check failed: shard_rec.nbytes == raw_data.length() (33233920 vs. 22720361) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation Stack trace: File "/Users/bbuf/工作目录/RWKV/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 262
> 
> ```
> at org.apache.tvm.Base.checkCall(Base.java:173)
> at org.apache.tvm.Function.invoke(Function.java:130)
> at ai.mlc.mlcllm.ChatModule.reload(ChatModule.java:43)
> at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:646)
> at ai.mlc.mlcchat.AppViewModel$ChatState$mainReloadChat$1$2.invoke(AppViewModel.kt:644)
> at ai.mlc.mlcchat.AppViewModel$ChatState.callBackend(AppViewModel.kt:547)
> at ai.mlc.mlcchat.AppViewModel$ChatState.mainReloadChat$lambda$3(AppViewModel.kt:644)
> at ai.mlc.mlcchat.AppViewModel$ChatState.$r8$lambda$JJKpoRMMpp77FzXKA0o00i8lgRA(Unknown Source:0)
> at ai.mlc.mlcchat.AppViewModel$ChatState$$ExternalSyntheticLambda3.run(Unknown Source:8)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
> at java.util.concurrent.FutureTask.run(FutureTask.java:264)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
> at java.lang.Thread.run(Thread.java:1012)
> ```
> 
> Error message: ValueError: Check failed: shard_rec.nbytes == raw_data.length() (33233920 vs. 22720361) : Parameters are not loaded properly. Please check your parameter shards and git lfs installation Stack trace: File "/Users/bbuf/工作目录/RWKV/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/ndarray_cache_support.cc", line 262

I also encountered this issue, it was due to the weights not being fully downloaded. You can uninstall the app and reinstall it, then download the weights again while using a proxy. Make sure not to switch the proxy or the network during the download.

**Comment by ThisisBillhe** [comment]
Can I download the weights from my PC and put them to some dir on my phone?

**Comment by BBuf** [comment]
> Can I download the weights from my PC and put them to some dir on my phone?

Certainly, you can use adb push to transfer the local weights to the path where the app stores the weights.

**Comment by ThisisBillhe** [comment]
Do you know where this path is? thanks!

**Comment by BBuf** [comment]
> Do you know where this path is? thanks!

It's probably under a folder named something like ai.mlc.llm in /storage.
